# Generated by Django 4.2.11 on 2024-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="vin",
            field=models.CharField(max_length=17),
        ),
    ]
