# Generated by Django 4.2.11 on 2024-04-24 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Manufacturer's name", max_length=100, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Manufacturers",
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Model's name", max_length=100)),
                (
                    "picture_url",
                    models.URLField(help_text="URL of the model's picture"),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        help_text="Manufacturer of the model",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="inventory.manufacturer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Automobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Color of the automobile", max_length=50
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Manufacturing year of the automobile"
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        help_text="Vehicle Identification Number",
                        max_length=17,
                        unique=True,
                    ),
                ),
                (
                    "sold",
                    models.BooleanField(
                        default=False, help_text="Is the automobile sold?"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model of the automobile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automobiles",
                        to="inventory.vehiclemodel",
                    ),
                ),
            ],
        ),
    ]
